development:
  adapter: postgresql
  encoding: unicode
  database: reclame_ai_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fabiano
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: reclame_ai_test
  pool: 5
  username: fabiano
  password:


production:
  database: reclame_ai_production
  username: reclame_ai
  password: <%= ENV['RECLAME_AI_DATABASE_PASSWORD'] %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
